### ISSUE TITLE
Declare browser support

### ISSUE THREAD

**Issue by milosdjakonovic** [Parasail-Health/parasail#2]
IMO, when developing such vital components like `CSS` frameworks, it is very important to let potential users what they can expect regarding this subject.

I've seen flexbox utilization - so no `IE` at all?

**Comment by melaniebmn** [comment]
Sorry, just realized that notifications were turned off. We are working on an update right now that will be done in the next few days - We will make sure to add a section that will talk about browser support since it is vital for choosing a CSS framework - thank you for pointing it out!
